language: node_js
sudo: false
node_js:
  - 10
install:
  - npm install
script:
  - npm run test
  - npm run lint

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true